NightOfTheLivingRuby!/lotto/config/routes.rb
Lotto::Application.routes.draw do
  resources :contestants , :except => [ :edit , :update , :show ] do
    collection do
      get 'winner'
    end
  end
  
  root :to => 'contestants#index' 
  
end

NightOfTheLivingRuby!/lotto/app/models/contestant.rb
class Contestant < ActiveRecord::Base
  
  validates_uniqueness_of :name
  
  def self.random
    unless count.zero?
      first :offset => rand(count)
    end
  end
  
end

NightOfTheLivingRuby!/lotto/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

NightOfTheLivingRuby!/lotto/app/controllers/contestants_controller.rb
class ContestantsController < ApplicationController
  
  before_filter :authenticate , :only => :destroy
  
  def index
    @contestants = Contestant.all
  end

  def new
    @contestant = Contestant.new
  end

  def create
    @contestant = Contestant.new params[:contestant]
    if @contestant.save
      redirect_to contestants_url , :notice => 'Contestant was successfully created.'
    else
      render :action => "new"
    end
  end

  def destroy
    @contestant = Contestant.find params[:id]
    @contestant.destroy
    redirect_to contestants_url
  end
  
  def winner
    @contestant = Contestant.random
    render :show
  end
  
private

  def authenticate
    authenticate_or_request_with_http_basic do |name,password|
      name == "admin" && password == "51a687202134a82b145b639aa10337c133369033"
    end
  end
  
end

NightOfTheLivingRuby!/lotto/app/helpers/application_helper.rb
module ApplicationHelper
end

NightOfTheLivingRuby!/lotto/app/helpers/contestants_helper.rb
module ContestantsHelper
end

NightOfTheLivingRuby!/lotto/app/views/contestants/_form.html.erb
<%= form_for(@contestant) do |f| %>
  <% if @contestant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contestant.errors.count, "error") %> prohibited this contestant from being saved:</h2>

      <ul>
      <% @contestant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

NightOfTheLivingRuby!/lotto/app/views/contestants/index.html.erb
<h1>Listing contestants</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>

<% @contestants.each do |contestant| %>
  <tr>
    <td><%= contestant.name %></td>
    <td><%= link_to 'Destroy', contestant , :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contestant', new_contestant_path %> |
<%= link_to 'Pick Winner' , winner_contestants_path %>

NightOfTheLivingRuby!/lotto/app/views/contestants/new.html.erb
<h1>New contestant</h1>

<%= render 'form' %>

<%= link_to 'Back', contestants_path %>

NightOfTheLivingRuby!/lotto/app/views/contestants/show.html.erb
<p id="notice"><%= notice %></p>

<h1>THE WINNER IS: <%= @contestant.name %></h1>

<%= link_to 'Back', contestants_path %>

NightOfTheLivingRuby!/lotto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lotto for Night Of The Living Ruby!</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>